#!/bin/bash
set -e

OPT="--disable-fontconfig \
	--disable-require-system-font-provider \
	--enable-directwrite"

if [ ! -f $SRC/libass*/configure ]; then
cd $SRC/libass*
./autogen.sh
cd -
fi

$SRC/libass*/configure $COMMON_OPTIONS $OPT
							
make install