#!/bin/sh
set -e

OPTS="--prefix=$SCRATCH/$ARCH \
	--exec-prefix=$SCRATCH/$ARCH \
	--disable-cplayer \
	--disable-lcms2 \
	--disable-lua \
	--disable-rubberband \
	--disable-zimg \
	--enable-libmpv-static \
	--enable-ios-gl \
	--enable-gl \
	--disable-javascript \
	--disable-libbluray \
	--disable-vapoursynth \
	--enable-uchardet \
	--enable-lgpl"

if [[ "$ENVIRONMENT" = "development" ]]; then
	OPTS="$OPTS --disable-optimize"
fi

cd $SRC/mpv*
#curl -L https://raw.githubusercontent.com/missdeer/daily-weekly-build/master/ios/wscript_build.py -o wscript_build.py
#curl -L https://raw.githubusercontent.com/missdeer/daily-weekly-build/master/ios/wscript -o wscript
#chmod a+x wscript_build.py
#chmod a+x wscript
pwd
ls -l
#curl -O -L https://github.com/mesonbuild/meson/raw/master/cross/iphone.txt
#meson setup --cross-file iphone.txt --default-library static -Diconv=disabled -Dlua=disabled -Dlibmpv=false -Dcplayer=false build
#meson compile -C build
./bootstrap.py
curl -sL -o war https://waf.io/waf-2.0.26
./waf configure $OPTS
./waf build -j `sysctl -n hw.logicalcpu`
