name: crashpad
on: 
  schedule:
    - cron:  '0 18 * * *'
  push:
    paths:
      - '.github/workflows/crashpad.yml'
  pull_request:
    paths:
      - '.github/workflows/crashpad.yml'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        msvc_arch: [x64, x86]
    env:
      targetName: crashpad-win-${{ matrix.msvc_arch }}
    steps:
      - name: Set up depot_tool
        shell: cmd
        run: |
          mkdir depot_tools
          cd depot_tools
          curl.exe -O -sSL https://storage.googleapis.com/chrome-infra/depot_tools.zip
          7z.exe x depot_tools.zip
          cd ..

      - name: Checkout crashpad
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          set PATH=%CD%\depot_tools;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
          mkdir crashpad
          cd crashpad
          path
          fetch crashpad

      - name: gn gen
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%CD%\depot_tools;%PATH%
          cd crashpad
          dir && cd
          cd crashpad
          dir && cd
          gn gen out\Default

      - name: build crashpad
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\
          Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%CD%\depot_tools;%PATH%
          cd crashpad
          dir && cd
          cd crashpad
          dir && cd
          ninja -C out\Default

      - name: archive binaries
        shell: cmd
        run: |
          mkdir bin
          pushd %CD%\crashpad\crashpad\out\Default
          for /r %a in (*.lib) do copy "%a" "%CD%\bin\" 
          for /r %a in (*.dll) do copy "%a" "%CD%\bin\" 
          for /r %a in (*.exe) do copy "%a" "%CD%\bin\" 
          popd

      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: bin
          name: crashpad-win-${{ matrix.msvc_arch }}
          
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Build transfer command
        run: |
          git clone --depth=1 https://github.com/missdeer/transfer.git gopath
          cd gopath
          go build -ldflags="-s -w" -o bin\transfer.exe
          cd ..

      - name: upload to own file server
        shell: cmd
        run: |
          set TRANSFER=%CD%\gopath\bin\transfer.exe
          7z.exe a ..\crashpad-win-${{ matrix.msvc_arch }}.7z bin
          dir
          curl -X POST -H "Content-Type: multipart/form-data" -F "originalFile=@crashpad-win-${{ matrix.msvc_arch }}.7z" ${{ secrets.FILE_SERVER }}
          echo %TRANSFER%
          "%TRANSFER%" -m upload -c ${{ secrets.FILE_SERVER3 }} -p quic crashpad-win-${{ matrix.msvc_arch }}.7z
