name: echo
on: 
  push:
    paths:
      - '.github/workflows/echo.yml'
  pull_request:
    paths:
      - '.github/workflows/echo.yml'

jobs:
  echo:
    runs-on: ubuntu-latest    
    steps:
      - run: a="${{ secrets.FILE_SERVER }}" && echo $a
      
      - run: a="echo ${{ secrets.FILE_SERVER2 }}" && echo $a
      
      - run: a="echo ${{ secrets.FILE_SERVER3 }}" && echo $a
      
      - run: a="echo ${{ secrets.CLANG_SERVER }}" && echo $a
      
