name: ipset
on: 
  schedule:
    - cron:  '0 4 * * *'
  push:
    paths:
      - '.github/workflows/ipset.yml'
  pull_request:
    paths:
      - '.github/workflows/ipset.yml'

      
jobs:
  route:
    runs-on: ubuntu-latest
    steps:          
      - name: Generate ipset files
        env:
          MAXMIND_LICENSEKEY: ${{ secrets.MAXMIND_LICENSEKEY }}    
        run: |
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${MAXMIND_LICENSEKEY}&suffix=zip" -o GeoLite2-Country-CSV.zip
          unzip GeoLite2-Country-CSV.zip
          find . -name 'GeoLite2-Country-CSV_*' -type d | while read dir; do mv $dir "GeoLite2-Country-CSV"; done
          cd GeoLite2-Country-CSV
          curl -o cnroute.txt -L https://cdn.jsdelivr.net/gh/17mon/china_ip_list@master/china_ip_list.txt
          awk -F ',' 'NR==FNR && $0 ~ /,IT,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > itroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,US,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > usroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,JP,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > jproute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,TW,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > twroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,HK,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > hkroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,SG,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > sgroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,KR,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > krroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,RU,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > ruroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,GB,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > gbroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,FR,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > frroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,DE,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > deroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,SE,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > seroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,ES,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > esroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,NL,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > nlroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,AS,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > asroute.txt
          cat cnroute.txt jproute.txt twroute.txt hkroute.txt krroute.txt sgroute.txt > combinedroutes.txt
          grep -v -F -f combinedroutes.txt asroute.txt > asroute_filtered.txt
          mv asroute_filtered.txt asroute.txt
          rm combinedroutes.txt
          awk -F ',' 'NR==FNR && $0 ~ /,EU,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > euroute.txt
          cat itroute.txt ruroute.txt gbroute.txt frroute.txt nlroute.txt seroute.txt esroute.txt deroute.txt > combinedroutes.txt
          grep -v -F -f combinedroutes.txt euroute.txt > euroute_filtered.txt
          mv euroute_filtered.txt euroute.txt
          rm combinedroutes.txt
          awk -F ',' 'NR==FNR && $0 ~ /,OC,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > ocroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,AF,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > afroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,SA,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > saroute.txt
          awk -F ',' 'NR==FNR && $0 ~ /,NA,/ {id=$1; next} NR!=FNR && $0 ~ id {split($1, arr, "/"); print arr[1]}' GeoLite2-Country-Locations-zh-CN.csv GeoLite2-Country-Blocks-IPv4.csv > naroute.txt
          grep -v -F -f usroute.txt naroute.txt > naroute_filtered.txt
          mv naroute_filtered.txt naroute.txt
          mkdir ../routes
          mv *route.txt ../routes/
          cd ../routes
          find . -name '*route.txt' -type f | while read f; do basename=${f##*/}; basename=${basename%.txt}; sed -i "s|^|add $basename |" $f; done
          
      - name: Upload to GitHub Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}    
        run: |    
          cd routes  
          git init
          git add .
          git config user.name "update-routes[bot]"
          git config user.email "update-routes[bot]@users.noreply.github.com"
          git commit -m "update routes at $(date)" .
          git push --force --quiet https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:routes        
