name: make media resolvers
on: 
  schedule:
    - cron:  '0 5 * * 1'
  push:
    paths:
      - '.github/workflows/media-resolvers.yml'
  pull_request:
    paths:
      - '.github/workflows/media-resolvers.yml'
jobs:
  make_resolvers:
    runs-on: windows-latest
    steps:
      - name: install pyinstaller
        shell: cmd
        run: |
          pip install pyinstaller

      - name: Set up Release Date
        run: echo "RELEASE_DATE=v$(Get-Date -Format "yyyy.MM.dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: make ykdl
        shell: cmd
        run: |
          git clone --depth=1 --single-branch --branch master https://github.com/SeaHOH/ykdl.git
          cd ykdl
          pyinstaller.exe cykdl\__main__.py --onefile --name ykdl 
          dir dist
          copy /y dist\ykdl.exe ..\ykdl.exe
          cd ..
    
      - name: upload ykdl artifact
        uses: actions/upload-artifact@v1
        with:
          path: ykdl.exe
          name: ykdl.exe
  
      - name: upload ykdl Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ykdl.exe
          asset_name: ykdl.exe
          release_name: ${{ env.RELEASE_DATE }}
          tag: ${{ env.RELEASE_DATE }}
          overwrite: true

      - name: make you-get
        shell: cmd
        run: |
          git clone --depth=1 --single-branch --branch develop https://github.com/soimort/you-get.git
          cd you-get
          pyinstaller.exe -F --path=src you-get
          dir dist
          copy /y dist\you-get.exe ..\you-get.exe
          cd ..
    
      - name: upload you-get artifact
        uses: actions/upload-artifact@v1
        with:
          path: you-get.exe
          name: you-get.exe
  
      - name: upload you-get Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: you-get.exe
          asset_name: you-get.exe
          release_name: ${{ env.RELEASE_DATE }}
          tag: ${{ env.RELEASE_DATE }}
          overwrite: true
  
      - name: make youtube-dl
        shell: cmd
        run: |
          git clone --depth=1 --single-branch --branch master https://github.com/ytdl-org/youtube-dl.git
          cd youtube-dl
          pyinstaller.exe youtube_dl\__main__.py --onefile --name youtube-dl 
          dir dist
          copy /y dist\youtube-dl.exe ..\youtube-dl.exe
          cd ..
    
      - name: upload youtube-dl artifact
        uses: actions/upload-artifact@v1
        with:
          path: youtube-dl.exe
          name: youtube-dl.exe
  
      - name: upload youtube-dl Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: youtube-dl.exe
          asset_name: youtube-dl.exe
          release_name: ${{ env.RELEASE_DATE }}
          tag: ${{ env.RELEASE_DATE }}
          overwrite: true
