name: notepad2
on: 
  schedule:
    - cron:  '0 23 * * *'
  push:
    paths:
      - '.github/workflows/notepad2.yml'
      - 'notepad2/**'
  pull_request:
    paths:
      - '.github/workflows/notepad2.yml'
      - 'notepad2/**'
      
env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7dff44ba-e3af-4448-841c-0d616c8da6e7/w_BaseKit_p_2024.1.0.595_offline.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/c95a3b26-fc45-496c-833b-df08b10297b9/w_HPCKit_p_2024.1.0.561_offline.exe
  WINDOWS_CPP_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common
  WINDOWS_DPCPP_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common
  CACHE_NUMBER: 6
  SAMPLES_TAG: 2024.1.0
  COMPILER_VERSION: 2024.1.0
  TBB_VERSION: 2021.12.0
  VS_VER: vs2022
            
jobs:
  notepad2-nightly-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        toolset: [cl, icx, clang-cl]
        msvc_arch: [x64]
        include:
          - toolset: cl
          - toolset: icx
          - toolset: clang-cl
            clang_link: https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.3/LLVM-18.1.3-win64.exe
    env:
      targetName: notepad2-${{ matrix.toolset }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      
      - name: Set up clang for Windows
        if: matrix.toolset == 'clang-cl'
        shell: cmd
        run: |
          mkdir llvm
          cd llvm
          curl.exe -o LLVM.exe -L ${{ matrix.clang_link }}
          7z.exe x LLVM.exe
          cd ..

      - name: cache intel install
        if: matrix.toolset == 'icx'
        id: cache-install
        uses: actions/cache@v2
        with:
          path: |
              C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat
              C:\Program Files (x86)\Intel\oneAPI\compiler
          key: install-${{ env.CACHE_NUMBER }}-${{ env.WINDOWS_HPCKIT_URL }}-${{ env.WINDOWS_CPP_COMPONENTS }}-compiler-${{ hashFiles('**/scripts/cache_exclude_windows.sh') }}

      - name: install intel
        if: steps.cache-install.outputs.cache-hit != 'true' && matrix.toolset == 'icx'
        run: |
          git clone --depth=1 https://github.com/oneapi-src/oneapi-ci.git oneapi-ci
          cd oneapi-ci
          scripts/install_windows.bat ${{ env.WINDOWS_HPCKIT_URL }} ${{ env.WINDOWS_CPP_COMPONENTS }}

      - name: restore registry on cache hit
        if: steps.cache-install.outputs.cache-hit == 'true' && matrix.toolset == 'icx'
        run:  |
          git clone --depth=1 https://github.com/oneapi-src/oneapi-ci.git oneapi-ci
          cd oneapi-ci
          scripts/restore_registry.bat ${{ env.COMPILER_VERSION }} ${{ env.TBB_VERSION }}

      - name: build
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          for /f "tokens=* usebackq" %%f in (`dir /b "C:\Program Files (x86)\Intel\oneAPI\compiler\" ^| findstr /V latest ^| sort`) do @set "LATEST_VERSION=%%f"
          echo %LATEST_VERSION%
          call "C:\Program Files (x86)\Intel\oneAPI\compiler\%LATEST_VERSION%\env\vars.bat"
          set PATH="C:\Program Files (x86)\Intel\oneAPI\compiler\%LATEST_VERSION%\bin\";%CD%\llvm\bin;%CD%\jom;%PATH%
          git clone --recursive https://github.com/zufuliu/notepad2.git notepad2-src
          copy notepad2\CMakeLists.txt notepad2-src\
          cd notepad2-src
          git apply ..\notepad2\notepad2.patch
          cd ..
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.toolset }} -DCMAKE_CXX_COMPILER=${{ matrix.toolset }} -G Ninja -S notepad2-src -B cmake-build
          cmake --build cmake-build --parallel --verbose
          mkdir bin
          copy cmake-build\notepad2.exe bin\
          copy cmake-build\metapath.exe bin\
          cd ..
          
      - name: copy oneAPI redist
        if: matrix.toolset == 'icx'
        shell: cmd
        run: |
          for /f "tokens=* usebackq" %%f in (`dir /b "C:\Program Files (x86)\Intel\oneAPI\compiler\" ^| findstr /V latest ^| sort`) do @set "LATEST_VERSION=%%f"
          echo %LATEST_VERSION%        
          copy /y "C:\Program Files (x86)\Intel\oneAPI\compiler\%LATEST_VERSION%\bin\libmmd.dll" bin\
          copy /y "C:\Program Files (x86)\Intel\oneAPI\compiler\%LATEST_VERSION%\bin\libiomp*md.dll" bin\
          
      - name: copy clang-cl redist
        if: matrix.toolset == 'clang-cl'
        shell: cmd
        run: |
          copy /y "%CD%\llvm\bin\lib*omp*.dll" bin\

      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: bin
          name: notepad2-${{ matrix.toolset }}

  notepad2-nightly-mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - mingw_arch: UCRT64
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            cmake_prefix_path: /ucrt64
            stdlib: /ucrt64/bin/libstdc++-6.dll
          - mingw_arch: CLANG64 
            mingw_prefix: mingw-w64-clang-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            cmake_prefix_path: /clang64
            stdlib: /clang64/bin/libc++.dll
          - mingw_arch: MINGW64
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            cmake_prefix_path: /mingw64
            stdlib: /mingw64/bin/libstdc++-6.dll
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install: ${{ matrix.mingw_prefix }}-toolchain ${{ matrix.mingw_prefix }}-cmake ${{ matrix.mingw_prefix }}-ninja ${{ matrix.mingw_prefix }}-${{ matrix.toolchains }}  ${{ matrix.mingw_prefix }}-clang ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd ${{ matrix.mingw_prefix }}-libb2

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          submodules: true
                     
      - name: prepare
        shell: cmd
        run: |
          git clone --recursive https://github.com/zufuliu/notepad2.git notepad2-src
          copy notepad2\CMakeLists.txt notepad2-src\
          cd notepad2-src
          git apply ..\notepad2\notepad2.patch
                    
      - name: build
        shell: msys2 {0}
        run: |
          env MSYSTEM=${{ matrix.mingw_arch }} PATH=/${{ matrix.mingw_arch }}/bin:/usr/bin:$PATH cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja -S notepad2-src -B ${{ matrix.mingw_prefix }}-build
          env MSYSTEM=${{ matrix.mingw_arch }} PATH=/${{ matrix.mingw_arch }}/bin:/usr/bin:$PATH cmake --build ${{ matrix.mingw_prefix }}-build --parallel --verbose
          mkdir bin
          env MSYSTEM=${{ matrix.mingw_arch }} PATH=/${{ matrix.mingw_arch }}/bin:/usr/bin:$PATH cp ${{ matrix.mingw_prefix }}-build/notepad2.exe bin/
          env MSYSTEM=${{ matrix.mingw_arch }} PATH=/${{ matrix.mingw_arch }}/bin:/usr/bin:$PATH cp ${{ matrix.mingw_prefix }}-build/metapath.exe bin/
          env PATH=$PATH:/${{ matrix.mingw_arch }}/bin ldd bin/notepad2.exe | awk -v mingwarch="${{ matrix.mingw_arch }}" '{ arch = tolower(mingwarch); path = tolower($0);  if (path ~ "=> /" arch) print $(NF-1) }' | while read -r libpath; do cp -r $libpath bin/; done
          
      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: bin
          name: notepad2-${{ matrix.mingw_prefix }}
