name: Windows
on: 
  schedule:
    - cron:  '0 17 * * *'
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  Windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-w64-mingw32.static, i686-w64-mingw32.static]
    steps:
      - name: prepare mxe
        run: |
          sudo apt-get update -qq ;
          sudo apt-get install -qq autopoint gperf intltool libltdl-dev libtool-bin lzip;
          git clone --depth=1 https://github.com/mxe/mxe mxe
          cd mxe
          echo "JOBS := 4" >> settings.mk
          echo "MXE_TARGETS := ${{ matrix.target }}" >> settings.mk
          make gcc ffmpeg libass jpeg lua luajit
          cd ..
      - name: checkout mpv
        run: |
          git clone --depth=1 https://github.com/mpv-player/mpv.git
      - name: build mpv
        run: |
          cd mpv
          ./bootstrap.py
          env PATH=$PWD/../mxe/usr/bin:$PATH DEST_OS=win32 TARGET=${{ matrix.target }} ./waf configure --enable-libmpv-shared 
          env PATH=$PWD/../mxe/usr/bin:$PATH DEST_OS=win32 TARGET=${{ matrix.target }} ./waf build
          cd ..
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          path: mpv/build
          name: ${{ matrix.target }}-mpv